package basic;
import java.util.Random;

public class Random_number {
       
	static Random rn = new Random();
	static int x = rn.nextInt(1, 100);
	
	public static void main(String[] args) {
		
		 System.out.println("random num generated by system is : " + x);

	}

}
